// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwwavpqhetsgrpsxzzpg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3d2F2cHFoZXRzZ3Jwc3h6enBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2MDYwMDUsImV4cCI6MjA3MDE4MjAwNX0.w5M5zN2Km3Osq3L-lEyg1AHELtyaTCV8WqCOJUdMsO0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});