// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iedrdbufhyobugewyxfx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImllZHJkYnVmaHlvYnVnZXd5eGZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5ODYyNTEsImV4cCI6MjA2NzU2MjI1MX0.TbMqVqrX6Qc8JcdQtFjwVEq3Q1kD-8Z65yK4eIaNBEs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});